# Generated by Django 4.2.9 on 2024-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=2)),
                ('college', models.CharField(max_length=32)),
                ('clazz', models.CharField(max_length=32)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('role', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户名',
                'db_table': 'tb_user',
                'ordering': ['account'],
            },
        ),
    ]
