# Generated by Django 4.2.9 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=2)),
                ('college', models.CharField(max_length=32)),
                ('clazz', models.CharField(max_length=32)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
