# Generated by Django 3.2.19 on 2024-06-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('username', models.CharField(max_length=100)),
                ('date_json', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
