# Generated by Django 3.2.19 on 2024-06-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
