# Generated by Django 3.2.19 on 2024-06-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_column='Tagname', max_length=200),
        ),
    ]
