# Generated by Django 3.2.19 on 2024-06-03 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
