# Generated by Django 3.2.19 on 2024-06-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0005_tag_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time', 'name']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
