# Generated by Django 3.2.19 on 2024-06-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0006_auto_20240603_0938'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='sz_table',
        ),
    ]
